---
title: "week1-discussion"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(here)
library(janitor)
library(usdata)
library(tidyverse)
library(lubridate)
```

```{r}
fracking <- read_csv(here("data", "registryupload_1.csv"))
```

```{r}
fracking_clean <- fracking %>%
  clean_names() %>%
  mutate(job_start_date = str_remove(job_start_date, " AM")) %>%
  mutate(job_end_date = str_remove(job_end_date, " AM")) %>%
  mutate(datetime_start = mdy_hms(job_start_date)) %>%
  mutate(year = year(datetime_start)) %>%
  select(datetime_start, year, state_name, well_name, total_base_water_volume) %>%
  mutate(state_name = str_to_title(state_name))

fracking_clean <- fracking_clean %>%
  filter(!str_detect(state_name, pattern = "\\?")) %>%
  mutate(state_name = ifelse(str_length(state_name) == 2,
    abbr2state(state_name),
    state_name)) %>%
  mutate(state_name = case_when(
    state_name == "Colordao" ~ "Colorado",
    state_name == "Penssylvania" ~ "Pennsylvania",
    state_name == "Norh Dakota" ~ "North Dakota",
    
    TRUE ~ state_name
  )) %>%
  filter(!state_name %in% c("Beaver", "Beckham", "Harper", "Hemphill", "Midland", "Red River", "Roosevelt", "Rusk", "State", "Ward"))
  
  


unique(fracking_clean$state_name)

```




















